trigger:
  - master

pool:
  name: 'Default'

variables:
  - group: Access_Token
  - name: region
    value: 'Saudi' # Add region input: Use 'Global' or 'Saudi'


steps:
  - checkout: self  # Check out the repository containing the Appknox task

  - script: |
      echo "Region selected: $(region)"
    displayName: 'Log Region Parameter'

  # Step 2: Run the Appknox security scan
  - task: Yashvi-Appknox.Appknox@2
    inputs:
      filepath: 'C:\Users\hirakdesai\Documents\GitHub\app-release-unsigned.apk'  # Path to the APK
      accessToken: '$(appknoxtoken)'  # Reference the Appknox access token from environment variables
      region: '$(region)'
      riskThreshold: 'critical'  # Risk threshold for scan
