trigger:
  - master

pool:
  name: 'Default'

steps:
  # Step 2: Run the Appknox security scan
  - task: appknox@2
    inputs:
      filepath: 'C:\Users\hirakdesai\Documents\GitHub\app-release-unsigned.apk'  # Path to the APK
      accessToken: '245d2ea50185c7660e9953b332f22950311b7fb9'
      # accessToken: '$(appknoxtoken)'  # Reference the Appknox access token from environment variables
      region: 'Global'  # Add region input: Use 'Global' or 'Saudi'
      riskThreshold: 'medium'  # Risk threshold for scan
