trigger:
  - master

pool:
  name: 'Default'  # Use 'Default' if you're using a self-hosted agent, or specify a different pool if needed

variables:
  - group: Access_Token  # This should contain 'appknoxtoken'

steps:
  - checkout: self  # Step 1: Check out the repository containing the Appknox task

  # Step 3: Run the Appknox security scan using Appknox task
  - task: Appknox@2
    inputs:
      filePath: 'C:\Users\hirakdesai\Documents\GitHub\app-release-unsigned.apk'
      accessToken: '$(appknoxtoken)'
      riskThreshold: 'high'
      region: 'global'
