trigger:
  - master

pool:
  name: 'Default'

variables:
  - group: Access_Token
  - name: region
    value: 'global'  # Use 'Global' or 'Saudi'
  - name: riskThreshold
    value: 'critical'  # Set your desired risk threshold

steps:
  - checkout: self  # Check out the repository

  # Log the selected region and risk threshold
  - script: |
      echo "Region selected: $(region)"
      echo "Risk Threshold: $(riskThreshold)"
    displayName: 'Log Region and Risk Threshold'

  # Run the Appknox security scan using Appknox Go on Windows
  - powershell: |
      $scanId = C:\Users\hirakdesai\Documents\GitHub\appknox-go\appknox.exe upload C:\Users\hirakdesai\Documents\GitHub\app-release-unsigned.apk --access-token $(appknoxtoken) --region $(region)
      Write-Host "Uploaded Scan ID: $scanId"
      C:\Users\hirakdesai\Documents\GitHub\appknox-go\appknox.exe cicheck $scanId --region $(region) --risk-threshold $(riskThreshold)
    displayName: 'Run Appknox Security Scan'
    env:
      appknoxtoken: '$(appknoxtoken)'
      region: '$(region)'
